const rugbyPlayers = [
  {
    id: 1,
    nome: 'Maya Steele',
    idade: 22,
    imagem: 'jogadora1.jpg',
    posicao: 'Scrum-half',
    numero: 9,
    equipe: 'Black Ferns',
    nacionalidade: 'Neozelandesa',
    condicaoFisica: {
      altura: '1,68m',
      peso: '63kg',
      velocidade40m: '5,2s',
      resistenciaCooper: '2800m',
    },
  },
  {
    id: 2,
    nome: 'Bernadette Wolloytz',
    idade: 21,
    imagem: 'jogadora2.jpg',
    posicao: 'Loosehead Prop',
    numero: 1,
    equipe: 'Black Ferns',
    nacionalidade: 'Canadense',
    condicaoFisica: {
      altura: '1,76m',
      peso: '78kg',
      velocidade40m: '5,8s',
      resistenciaCooper: '2650m',
    },
  },
  {
    id: 3,
    nome: 'Penny Hofsteder',
    idade: 19,
    imagem: 'jogadora3.jpg',
    posicao: 'Hooker',
    numero: 2,
    equipe: 'Black Ferns',
    nacionalidade: 'Neozelandesa',
    condicaoFisica: {
      altura: '1,74m',
      peso: '72kg',
      velocidade40m: '5,0s',
      resistenciaCooper: '2260m',
    },
  },
  {
    id: 4,
    nome: 'Anastasia Morland',
    idade: 23,
    imagem: 'jogadora4.jpg',
    posicao: 'Prop',
    numero: 3,
    equipe: 'Black Ferns',
    nacionalidade: 'Italiana',
    condicaoFisica: {
      altura: '1,72m',
      peso: '68kg',
      velocidade40m: '4,7s',
      resistenciaCooper: '2500m',
    },
  },
  {
    id: 5,
    nome: 'Amy Estanislau',
    idade: 20,
    imagem: 'jogadora5.jpg',
    posicao: 'Lock',
    numero: 4,
    equipe: 'Black Ferns',
    nacionalidade: 'Polonesa',
    condicaoFisica: {
      altura: '1,85m',
      peso: '79kg',
      velocidade40m: '5,1s',
      resistenciaCooper: '2410m',
    },
  },
  {
    id: 6,
    nome: 'Luciana Ferreira',
    idade: 24,
    imagem: 'jogadora6.jpg',
    posicao: 'Centre',
    numero: 12,
    equipe: 'Black Ferns',
    nacionalidade: 'Brasileira',
    condicaoFisica: {
      altura: '1,70m',
      peso: '64kg',
      velocidade40m: '4,9s',
      resistenciaCooper: '2600m',
    },
  },
  {
    id: 7,
    nome: 'Sophie McKenna',
    idade: 25,
    imagem: 'jogadora7.jpg',
    posicao: 'Wing',
    numero: 11,
    equipe: 'Black Ferns',
    nacionalidade: 'Neozelandesa',
    condicaoFisica: {
      altura: '1,78m',
      peso: '68kg',
      velocidade40m: '4,4s',
      resistenciaCooper: '2700m',
    },
  },
  {
    id: 8,
    nome: 'Camila Santos',
    idade: 26,
    imagem: 'jogadora8.jpg',
    posicao: 'Fullback',
    numero: 15,
    equipe: 'Black Ferns',
    nacionalidade: 'Brasileira',
    condicaoFisica: {
      altura: '1,72m',
      peso: '66kg',
      velocidade40m: '4,6s',
      resistenciaCooper: '2750m',
    },
  },
];

export default rugbyPlayers;
